// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57Ez1gSWZZTKkzySEqSeYLPj6zaNeBbU',
    appId: '1:889547234056:android:dee7cd147f8b58139ceabd',
    messagingSenderId: '889547234056',
    projectId: 'we-chat-2d974',
    storageBucket: 'we-chat-2d974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUhbAZ3nE6dJkTFZN6FWqo0gPt4McQVA',
    appId: '1:889547234056:ios:3af66b333e65b8879ceabd',
    messagingSenderId: '889547234056',
    projectId: 'we-chat-2d974',
    storageBucket: 'we-chat-2d974.appspot.com',
    androidClientId: '889547234056-3noj6n28v2u3lli2jqvmn60n7krb9n2p.apps.googleusercontent.com',
    iosClientId: '889547234056-hg3ccqn6d0a96udmr5pl6qd9obmek2ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChatApp',
  );

}